---
- name: Instalar Prometheus e Grafana no Debian
  hosts: debian  # Nome do host definido no Vagrantfile para a máquina Debian

  become: true  # Permite a execução de comandos como superusuário

  tasks:
    - name: Adicionar Prometheus APT repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Adicionar Prometheus APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: yes

    - name: Instalar Prometheus e Grafana
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - prometheus
        - grafana

    - name: Iniciar e habilitar Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Iniciar e habilitar Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
